### ISSUE TITLE
Could not find artifact hm.zelha:particlesfx:jar:1.21

### ISSUE THREAD

**Issue by BuggyAl** [hmzel/ParticleSFX#3]
The most recent update seems to have broken the Maven dependency, updated instructions on the README.md page would be appreciated!

**Comment by BuggyAl** [comment]
The [list of versions](https://github.com/hmzel/ParticleSFX/packages/1878252/versions) on the README is now deleted.

**Comment by hmzel** [comment]
the dependency seems to be working fine- i completely deleted the hm.zelha.x folder in my .m2 folder and then reloaded maven and it installed with seemingly no issue, so im assuming the only problem is the broken link in the readme from deleting and re-uploading the package, which i just fixed :)
